name: Generate Trophy Card

on:
schedule:
# Every 12 hours
- cron: "0 */12 * * *"

workflow_dispatch:

push:
branches:
- main

concurrency:
group: trophy-generation
cancel-in-progress: true

jobs:
generate:
name: Generate GitHub Trophy
runs-on: ubuntu-latest
timeout-minutes: 10

```
permissions:
  contents: write

steps:
  - name: Generate trophy.svg
    uses: Erik-Donath/github-profile-trophy@feature/generate-svg
    with:
      username: ${{ github.repository_owner }}
      file: dist/trophy.svg
      token: ${{ secrets.GITHUB_TOKEN }}

      theme: dracula

      max-rows: 1

      margin-width: 8
      margin-height: 8

      no-background: false
      no-frame: false

  - name: Deploy trophy.svg
    uses: crazy-max/ghaction-github-pages@v4
    with:
      target_branch: trophy-output
      build_dir: dist
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
